apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-configmap
data:
  settings: {{ .Values.mirai.miraiApiHttp.settings | toYaml | quote }}
  {{- range $.Values.mirai.configurations }}
  {{ .name }}: {{ .content | quote }}
  {{- end }}
  {{- with .Values.unidbgFetchSign.enabled }}
  {{- $fullName := include "template.fullname" $ }}
  kfc: |-
    {
      "8.9.63": {
          "base_url": "http://{{$fullName}}-sign:8080",
          "type": "fuqiuluo/unidbg-fetch-qsign",
          "key": "114514"
      }
    }
  {{- end }}
  {{- with not .Values.unidbgFetchSign.enabled }}
  kfc: {{ .Values.unidbgFetchSign.kfc }}
  {{- end }}
