apiVersion: v1
kind: Secret
type: Opaque
immutable: false
data:
  autoLoginAccounts: >-
   {{ .Values.mirai.autoLoginAccounts | toYaml | b64enc }}
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.mirai.autoLoginAccounts.secretName }}


