{{- if $.Values.unidbgFetchSign.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "template.fullname" . }}
  labels:
    {{- include "template.signLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "template.signSelectorLabels" . | nindent 6 }}
  spec:
    {{- with .Values.imagePullSecrets }}
    imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    containers:
      - 
        name: {{ quote $.Values.unidbgFetchSign.name | default "unidbg-fetch-sign" }}
        image: {{ $.Values.unidbgFetchSign.image | default "unidbg-fetch-sign" }}
        imagePullPolicy: {{ .Values.unidbgFetchSign.pullPolicy }}
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}