{{- if $.Values.unidbgFetchSign.enabled -}}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "template.fullname" . }}-sign
  labels:
    {{- include "template.signLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.unidbgFetchSign.port | default 8080 }}
      targetPort: http
      protocol: TCP
      name: http-sing
  selector:
    {{- include "template.signSelectorLabels" . | nindent 4 }}
{{- end }}