nameOverride:
fullnameOverride:

mirai:
  name: mirai
  # 默认镜像 mirai 2.1.2 需要的可以升级，使用mirai文件夹那个Dockerfile就能打出来
  image: registry.cn-beijing.aliyuncs.com/zero-tools/mirai:latest
  pullPolicy: Always

  # 是否启用bot登录状态持久化？
  storageBots:
    enabled: true
    name: mirai-bot-pvc
    size: 500Mi

  # 是否启用日志持久化？
  storageLogs:
    enabled: true
    name: mirai-log-pvc
    size: 500Mi

  # 暴露mirai-api-http
  miraiApiHttp:
    enabled: true
    # 这部分设置会存入  
    # 并会在mirai容器mount的文件中生成 /mirai/net.mamoe.mirai-api-http/setting.yml
    # 具体可配置内容见 https://github.com/project-mirai/mirai-api-http/tree/e9d5609b1cd580217a868f2daa789360283ba289
    # 注意需要匹配mirai容器中安装的版本
    settings:
      adapters: 
        - http
        - ws
      debug: false
      enableVerify: false
      verifyKey: 114514
      adapterSettings:
        http:
          host: 0.0.0.0
          port: 19999
          cors: ["*"]
        ws:
          host: 0.0.0.0
          port: 19999
    # 调整服务暴露方式，默认是 service/cluster ip
    # 需要的话可以自己加 ingress
    service:
      enabled: true
  
  # 自动生成的配置文件，其他的配置可以在这里设置
  configurations:
    - name: accountLogin
      path: config/Console/AutoLogin.yml
      content: |-
        accounts:
        - account: 123456
          password: 
            kind: PLAIN
            value: pwd
          configuration: 
            enable: true
    - name: signPhoneProfile
      path: android_phone.json
      content: |-
        {
          "apk_id": "com.tencent.mobileqq",
          "app_id": 537185007,
          "sub_app_id": 537185007,
          "app_key": "0S200MNJT807V3GE",
          "sort_version_name": "8.9.90.13250",
          "build_time": 1697015435,
          "apk_sign": "a6b745bf24a2c277527716f6f36eb68d",
          "sdk_version": "6.0.0.2556",
          "sso_version": 21,
          "misc_bitmap": 150470524,
          "main_sig_map": 16724722,
          "sub_sig_map": 66560,
          "dump_time": "1697015435",
          "qua": "V1_AND_SQ_8.9.90_4938_YYB_D",
          "protocol_type": 1
        }
    - name: signPhoneProfile
      path: android_pad.json
      content: |-
        {
          "apk_id": "com.tencent.mobileqq",
          "app_id": 537185046,
          "sub_app_id": 537185046,
          "app_key": "0S200MNJT807V3GE",
          "sort_version_name": "8.9.90.13250",
          "build_time": 1697015435,
          "apk_sign": "a6b745bf24a2c277527716f6f36eb68d",
          "sdk_version": "6.0.0.2556",
          "sso_version": 21,
          "misc_bitmap": 150470524,
          "main_sig_map": 16724722,
          "sub_sig_map": 66560,
          "dump_time": "1697015435",
          "qua": "V1_AND_SQ_8.9.90_4938_YYB_D",
          "protocol_type": 6
        }

# 这个自带的签名就只支持内网了，需要的自己加 ingress
unidbgFetchSign:
  enabled: true
  # 签名镜像也可以自己替换
  image: registry.cn-beijing.aliyuncs.com/zero-tools/unidbg-fetch-qsign:latest
  port: 8080
  pullPolicy: Always
  version: 8.9.90
  # 如果enabled: false使用自己的签名服务
  # 则需要自己传入 KFCFactory.json的内容
  # true的时候传入无效
  kfc: ""
imagePullSecrets: []
selectorLabels: []
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}